"""Model-constraint tests: dedup key, api_key uniqueness, pricing history."""

from __future__ import annotations

from datetime import timedelta

import pytest
from django.db import IntegrityError, transaction
from django.utils import timezone

from apps.accounts.models import OperatorProfile, User
from apps.billing.models import PricingSetting, PricingSettingHistory
from apps.calls.models import CallRecord
from apps.companies.models import Company

pytestmark = pytest.mark.django_db


@pytest.fixture
def company() -> Company:
    return Company.objects.create(name="Constraint Co", slug="constraint-co")


def _make_call(company: Company, call_id: str) -> CallRecord:
    return CallRecord.all_objects.create(
        company=company,
        call_id=call_id,
        call_type=CallRecord.CallType.OUTBOUND,
        call_status=CallRecord.CallStatus.ANSWERED,
        from_number="+998998887766",
        to_number="+998901234567",
        counterparty_number="+998901234567",
        duration=30,
        start_time=timezone.now() - timedelta(minutes=5),
    )


class TestCallDedup:
    def test_duplicate_call_id_same_company_raises(self, company: Company) -> None:
        _make_call(company, "dup-1")
        with pytest.raises(IntegrityError), transaction.atomic():
            _make_call(company, "dup-1")

    def test_same_call_id_different_company_is_fine(self, company: Company) -> None:
        other = Company.objects.create(name="Other Co", slug="other-co")
        _make_call(company, "shared-id")
        _make_call(other, "shared-id")  # no error — dedup is per company
        assert CallRecord.all_objects.filter(call_id="shared-id").count() == 2


class TestApiKeyUnique:
    def test_duplicate_api_key_raises(self, company: Company) -> None:
        u1 = User.objects.create_user(username="op1", company=company)
        u2 = User.objects.create_user(username="op2", company=company)
        OperatorProfile.all_objects.create(
            company=company, user=u1, user_name="op1", api_key="fixed-key"
        )
        with pytest.raises(IntegrityError), transaction.atomic():
            OperatorProfile.all_objects.create(
                company=company, user=u2, user_name="op2", api_key="fixed-key"
            )

    def test_api_key_autogenerated_and_distinct(self, company: Company) -> None:
        u1 = User.objects.create_user(username="op3", company=company)
        u2 = User.objects.create_user(username="op4", company=company)
        p1 = OperatorProfile.all_objects.create(company=company, user=u1, user_name="op3")
        p2 = OperatorProfile.all_objects.create(company=company, user=u2, user_name="op4")
        assert p1.api_key and p2.api_key and p1.api_key != p2.api_key


class TestPricingHistory:
    def test_history_row_on_create_and_change(self) -> None:
        setting = PricingSetting.objects.create(price_per_operator_uzs=50000, trial_days=14)
        assert setting.history.count() == 1  # creation snapshot

        setting.price_per_operator_uzs = 60000
        setting.save()
        assert setting.history.count() == 2
        latest = setting.history.first()
        assert latest is not None
        assert latest.price_per_operator_uzs == 60000

    def test_no_history_row_when_nothing_tracked_changes(self) -> None:
        setting = PricingSetting.objects.create(price_per_operator_uzs=50000, trial_days=14)
        setting.save()  # touch without changing tracked fields
        assert PricingSettingHistory.objects.filter(setting=setting).count() == 1

    def test_single_global_row_enforced(self) -> None:
        PricingSetting.objects.create(price_per_operator_uzs=50000, trial_days=14)
        with pytest.raises(IntegrityError), transaction.atomic():
            PricingSetting.objects.create(price_per_operator_uzs=70000, trial_days=7)
