# Generated by Django 5.1.5 on 2026-09-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingnotification_dailycharge_monthlystatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingnotification',
            name='kind',
            field=models.CharField(choices=[('charge_settled', 'Monthly charge deducted'), ('payment_due', 'Payment due'), ('payment_requested', 'Payment request submitted'), ('payment_received', 'Payment received'), ('tariff_changed', 'Tariff changed'), ('blocked', 'Access blocked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('manual', 'Bank / Naqd')], max_length=10),
        ),
    ]
