# Generated by Django 5.1.5 on 2026-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingnotification_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingnotification',
            name='kind',
            field=models.CharField(choices=[('charge_settled', 'Monthly charge deducted'), ('payment_due', 'Payment due'), ('payment_requested', 'Payment request submitted'), ('payment_received', 'Payment received'), ('payment_refunded', 'Payment refunded'), ('tariff_changed', 'Tariff changed'), ('blocked', 'Access blocked')], max_length=20),
        ),
    ]
