# Generated by Django 5.1.5 on 2026-08-14 05:39

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified'),
        ('companies', '0002_company_api_key_company_feature_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcard',
            name='recording_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(default=False, help_text='Company-level admin (cabinet settings, deletes)'),
        ),
        migrations.CreateModel(
            name='OperatorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='accounts.operatorgroup'),
        ),
        migrations.AddConstraint(
            model_name='operatorgroup',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_group_per_company'),
        ),
    ]
