# Generated by Django 5.1.5 on 2026-08-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='company',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
