# Generated by Django 5.1.5 on 2026-08-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_api_key_company_feature_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='audio_retention_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
