# Generated by Django 5.1.5 on 2026-08-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_audio_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='acquired_via',
            field=models.CharField(choices=[('self_signup', 'Self signup'), ('referral_link', 'Referral link'), ('integrator_manual', 'Registered by integrator')], default='self_signup', max_length=20),
        ),
    ]
