# Generated by Django 5.1.5 on 2026-08-14 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_acquired_via'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='integrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='partners.integrator'),
        ),
    ]
