# Generated by Django 5.1.5 on 2026-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_integrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='UZ', help_text='ISO 3166-1 alpha-2', max_length=2),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Tashkent', max_length=64),
        ),
    ]
