# Generated by Django 5.1.5 on 2026-09-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_country_company_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='balance_uzs',
            field=models.BigIntegerField(default=0),
        ),
    ]
