# Generated by Django 5.1.5 on 2026-08-14 13:00

import apps.partners.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('companies', '0004_company_acquired_via'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Person or organisation name', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('referral_code', models.CharField(default=apps.partners.models._referral_code, max_length=12, unique=True)),
                ('cashback_percent_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payout_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integrator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_uzs', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='partners.integrator')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_cashback_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('cashback_months_limit', models.PositiveSmallIntegerField(default=12, help_text="Accrue cashback only for the company's first N months")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSettingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_cashback_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cashback_months_limit', models.PositiveSmallIntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='partners.platformsetting')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CashbackAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_uzs', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('accrued', 'Accrued'), ('reversed', 'Reversed (refund)'), ('paid_out', 'Paid out')], default='accrued', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_accruals', to='companies.company')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_accrual', to='billing.payment')),
                ('integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='partners.integrator')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_accruals', to='partners.payoutrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['integrator', 'status', '-created_at'], name='partners_ca_integra_ac0c92_idx'), models.Index(fields=['company', '-created_at'], name='partners_ca_company_fe7624_idx')],
            },
        ),
    ]
