# Generated by Django 5.1.5 on 2026-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='min_payout_uzs',
            field=models.PositiveBigIntegerField(default=50000, help_text='Minimum payout request amount'),
        ),
    ]
