# Generated by Django 5.1.5 on 2026-09-02 13:23

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_integrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('site_url', models.URLField()),
                ('logo_key', models.CharField(blank=True, default='', help_text='MinIO key', max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CRM catalog entries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrmIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('amocrm', 'amoCRM / Kommo'), ('bitrix24', 'Bitrix24'), ('odoo', 'Odoo')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_status', models.CharField(blank=True, default='', max_length=10)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('company', 'provider'), name='uniq_integration_per_company')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
