# Generated by Django 5.1.5 on 2026-08-13 18:10

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=128)),
                ('server_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('call_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], max_length=10)),
                ('call_status', models.CharField(choices=[('answered', 'Answered'), ('no_answer', 'No answer'), ('busy', 'Busy'), ('failed', 'Failed')], max_length=10)),
                ('from_number', models.CharField(max_length=20)),
                ('from_name', models.CharField(blank=True, max_length=200, null=True)),
                ('to_number', models.CharField(max_length=20)),
                ('to_name', models.CharField(blank=True, max_length=200, null=True)),
                ('operator_number', models.CharField(blank=True, max_length=20, null=True)),
                ('operator_number_missing', models.BooleanField(default=False)),
                ('counterparty_number', models.CharField(max_length=20)),
                ('counterparty_name', models.CharField(blank=True, max_length=200, null=True)),
                ('resolved_name', models.CharField(blank=True, help_text='Backend contact-catalog override (§5.4), kept separate for audit', max_length=200, null=True)),
                ('sim_slot', models.SmallIntegerField(default=-1)),
                ('duration', models.PositiveIntegerField(help_text='seconds')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='accounts.device')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='accounts.operatorprofile')),
            ],
            options={
                'ordering': ['-start_time'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CallAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('primary', 'Primary (phone recording)'), ('realtime', 'Realtime (microphone)')], default='primary', max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('object_key', models.CharField(help_text='MinIO object key', max_length=500)),
                ('content_type', models.CharField(default='audio/ogg', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='calls.callrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='E.164, normalized', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='calls.contact')),
            ],
        ),
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=24)),
                ('log_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_logs', to='accounts.operatorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['company', '-created_at'], name='calls_applo_company_387e8f_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['company', '-start_time'], name='calls_callr_company_bcf0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['company', 'operator', '-start_time'], name='calls_callr_company_4317ae_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['company', 'counterparty_number'], name='calls_callr_company_4403f5_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['company', 'call_type', 'call_status'], name='calls_callr_company_841f82_idx'),
        ),
        migrations.AddConstraint(
            model_name='callrecord',
            constraint=models.UniqueConstraint(fields=('company', 'call_id'), name='uniq_call_id_per_company'),
        ),
        migrations.AddConstraint(
            model_name='callaudio',
            constraint=models.UniqueConstraint(fields=('call', 'kind'), name='uniq_audio_kind_per_call'),
        ),
        migrations.AddIndex(
            model_name='contactphone',
            index=models.Index(fields=['number'], name='calls_conta_number_fc89f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactphone',
            constraint=models.UniqueConstraint(fields=('contact', 'number'), name='uniq_phone_per_contact'),
        ),
    ]
