# Generated by Django 5.1.5 on 2026-08-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='end_time_local',
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='start_time_local',
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
